package com.wimilee.stock.entity;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * t_trade_account
 * @author:wimilee
 * @date:Mon Jun 20 11:06:21 CST 2022
 *
 * @mbg.generated Mon Jun 20 11:06:21 CST 2022
 */
public class TTradeAccount implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_trade_account.id
     *
     * @mbg.generated Mon Jun 20 11:06:21 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_trade_account.userId
     *
     * @mbg.generated Mon Jun 20 11:06:21 CST 2022
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_trade_account.accountNo
     *
     * @mbg.generated Mon Jun 20 11:06:21 CST 2022
     */
    private String accountNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_trade_account.balance
     *
     * @mbg.generated Mon Jun 20 11:06:21 CST 2022
     */
    private Double balance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_trade_account.tradeGroupId
     *
     * @mbg.generated Mon Jun 20 11:06:21 CST 2022
     */
    private Long tradeGroupId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_trade_account.active_time
     *
     * @mbg.generated Mon Jun 20 11:06:21 CST 2022
     */
    private Date active_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_trade_account.status
     *
     * @mbg.generated Mon Jun 20 11:06:21 CST 2022
     */
    private Byte status;

    /**
     *
     * @mbg.generated Mon Jun 20 11:06:21 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * 主键标识
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_account.id
     *
     * @param id the value for t_trade_account.id
     *
     * @mbg.generated Mon Jun 20 11:06:21 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 用户ID
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_account.userId
     *
     * @param userId the value for t_trade_account.userId
     *
     * @mbg.generated Mon Jun 20 11:06:21 CST 2022
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * 交易账号
    public String getAccountNo() {
        return accountNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_account.accountNo
     *
     * @param accountNo the value for t_trade_account.accountNo
     *
     * @mbg.generated Mon Jun 20 11:06:21 CST 2022
     */
    public void setAccountNo(String accountNo) {
        this.accountNo = accountNo == null ? null : accountNo.trim();
    }

    /**
     * 余额
    public Double getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_account.balance
     *
     * @param balance the value for t_trade_account.balance
     *
     * @mbg.generated Mon Jun 20 11:06:21 CST 2022
     */
    public void setBalance(Double balance) {
        this.balance = balance;
    }

    /**
     * 账户组ID
    public Long getTradeGroupId() {
        return tradeGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_account.tradeGroupId
     *
     * @param tradeGroupId the value for t_trade_account.tradeGroupId
     *
     * @mbg.generated Mon Jun 20 11:06:21 CST 2022
     */
    public void setTradeGroupId(Long tradeGroupId) {
        this.tradeGroupId = tradeGroupId;
    }

    /**
     * 开户时间
    public Date getActive_time() {
        return active_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_account.active_time
     *
     * @param active_time the value for t_trade_account.active_time
     *
     * @mbg.generated Mon Jun 20 11:06:21 CST 2022
     */
    public void setActive_time(Date active_time) {
        this.active_time = active_time;
    }

    /**
     * 状态(0:有效， 1：锁定， 2：禁用）
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_account.status
     *
     * @param status the value for t_trade_account.status
     *
     * @mbg.generated Mon Jun 20 11:06:21 CST 2022
     */
    public void setStatus(Byte status) {
        this.status = status;
    }
}