package com.wimilee.stock.entity;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * t_trade_user
 * @author:wimilee
 * @date:Mon Jun 20 11:06:21 CST 2022
 *
 * @mbg.generated Mon Jun 20 11:06:21 CST 2022
 */
public class TTradeUser implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_trade_user.id
     *
     * @mbg.generated Mon Jun 20 11:06:21 CST 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_trade_user.userNo
     *
     * @mbg.generated Mon Jun 20 11:06:21 CST 2022
     */
    private String userNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_trade_user.name
     *
     * @mbg.generated Mon Jun 20 11:06:21 CST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_trade_user.userPwd
     *
     * @mbg.generated Mon Jun 20 11:06:21 CST 2022
     */
    private String userPwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_trade_user.phone
     *
     * @mbg.generated Mon Jun 20 11:06:21 CST 2022
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_trade_user.companyId
     *
     * @mbg.generated Mon Jun 20 11:06:21 CST 2022
     */
    private Long companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_trade_user.email
     *
     * @mbg.generated Mon Jun 20 11:06:21 CST 2022
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_trade_user.address
     *
     * @mbg.generated Mon Jun 20 11:06:21 CST 2022
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_trade_user.lastLoginIp
     *
     * @mbg.generated Mon Jun 20 11:06:21 CST 2022
     */
    private String lastLoginIp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_trade_user.lastLoginTime
     *
     * @mbg.generated Mon Jun 20 11:06:21 CST 2022
     */
    private Date lastLoginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_trade_user.status
     *
     * @mbg.generated Mon Jun 20 11:06:21 CST 2022
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_trade_user.createTime
     *
     * @mbg.generated Mon Jun 20 11:06:21 CST 2022
     */
    private Date createTime;

    /**
     *
     * @mbg.generated Mon Jun 20 11:06:21 CST 2022
     */
    private static final long serialVersionUID = 1L;

    /**
     * 主键标识
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_user.id
     *
     * @param id the value for t_trade_user.id
     *
     * @mbg.generated Mon Jun 20 11:06:21 CST 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * 用户编号
    public String getUserNo() {
        return userNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_user.userNo
     *
     * @param userNo the value for t_trade_user.userNo
     *
     * @mbg.generated Mon Jun 20 11:06:21 CST 2022
     */
    public void setUserNo(String userNo) {
        this.userNo = userNo == null ? null : userNo.trim();
    }

    /**
     * 用户名称
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_user.name
     *
     * @param name the value for t_trade_user.name
     *
     * @mbg.generated Mon Jun 20 11:06:21 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * 用户密码
    public String getUserPwd() {
        return userPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_user.userPwd
     *
     * @param userPwd the value for t_trade_user.userPwd
     *
     * @mbg.generated Mon Jun 20 11:06:21 CST 2022
     */
    public void setUserPwd(String userPwd) {
        this.userPwd = userPwd == null ? null : userPwd.trim();
    }

    /**
     * 电话号码
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_user.phone
     *
     * @param phone the value for t_trade_user.phone
     *
     * @mbg.generated Mon Jun 20 11:06:21 CST 2022
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * 公司ID
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_user.companyId
     *
     * @param companyId the value for t_trade_user.companyId
     *
     * @mbg.generated Mon Jun 20 11:06:21 CST 2022
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    /**
     * 邮箱
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_user.email
     *
     * @param email the value for t_trade_user.email
     *
     * @mbg.generated Mon Jun 20 11:06:21 CST 2022
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * 地址
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_user.address
     *
     * @param address the value for t_trade_user.address
     *
     * @mbg.generated Mon Jun 20 11:06:21 CST 2022
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * 最近一次用户登陆IP
    public String getLastLoginIp() {
        return lastLoginIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_user.lastLoginIp
     *
     * @param lastLoginIp the value for t_trade_user.lastLoginIp
     *
     * @mbg.generated Mon Jun 20 11:06:21 CST 2022
     */
    public void setLastLoginIp(String lastLoginIp) {
        this.lastLoginIp = lastLoginIp == null ? null : lastLoginIp.trim();
    }

    /**
     * 最近一次登陆时间
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_user.lastLoginTime
     *
     * @param lastLoginTime the value for t_trade_user.lastLoginTime
     *
     * @mbg.generated Mon Jun 20 11:06:21 CST 2022
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * 状态(0:有效， 1：锁定， 2：禁用）
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_user.status
     *
     * @param status the value for t_trade_user.status
     *
     * @mbg.generated Mon Jun 20 11:06:21 CST 2022
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * 创建时间
    public Date getcreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_trade_user.createTime
     *
     * @param createTime the value for t_trade_user.createTime
     *
     * @mbg.generated Mon Jun 20 11:06:21 CST 2022
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}