package com.wimilee.stock.dao;

import com.wimilee.stock.entity.TTradeUser;

public interface TTradeUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trade_user
     *
     * @mbg.generated Mon Jun 20 11:06:21 CST 2022
     */
    int insert(TTradeUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trade_user
     *
     * @mbg.generated Mon Jun 20 11:06:21 CST 2022
     */
    int insertSelective(TTradeUser record);
}