package com.wimilee.stock.dao;

import com.wimilee.stock.entity.TTradeAccount;

public interface TTradeAccountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trade_account
     *
     * @mbg.generated Mon Jun 20 11:06:21 CST 2022
     */
    int insert(TTradeAccount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_trade_account
     *
     * @mbg.generated Mon Jun 20 11:06:21 CST 2022
     */
    int insertSelective(TTradeAccount record);
}